### ISSUE TITLE
Time zones don't match up.

### ISSUE THREAD

**Issue by blakemorgan** [byu-oit/github-action-end-standard-change#18]
See https://github.com/byu-oit/github-action-start-standard-change/issues/29

**Comment by GaryGSC** [comment]
It looks like this has been going on for a while.

When we start the standard change, we don't specify a start time - it's assumed based on when we make the call.

When we end the change, I see that [we go out of our way to create a timestamp in ServiceNow's format, in America/Denver time](https://github.com/byu-oit/github-action-end-standard-change/blob/d7807a1d292fb80319be5fefaa9fcc59f3af3e65/index.js#L8-L14). Looks like we can now get rid of that timezone calculation and instead provide a timestamp in UTC.
